[package]
name = "openh264-sys"
version = "1.8.0"
authors = ["luozijun <luozijun.assistant@gmail.com>"]
edition = "2018"
links = "openh264"
build = "build.rs"

[dependencies]


[build-dependencies]
bindgen = "0.40"
pkg-config = "0.3"
